pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "chart.js", to: "https://cdn.jsdelivr.net/npm/chart.js@4.4.7/+esm"
pin "chart.js/auto", to: "https://cdn.jsdelivr.net/npm/chart.js@4.4.7/auto/+esm"
pin_all_from "app/javascript/controllers", under: "controllers"
